# logging
logging:
  config: classpath:log/logback.xml

#endpoints.health.enabled=true
#endpoints.health.path="/health"
#endpoints.health.id=health
#endpoints.health.sensitive=true

#mybatis:
#  mapper-locations: classpath:sqlMap/*.xml
#  typeAliasesPackage: com.marketing.web.mapper

spring:
  profiles: dev
  datasource:
    #type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rdsyvf3ii0q5sy1qr9u0public.mysql.rds.aliyuncs.com:3306/maywant
    username: lives
    password: livesALL2015
#    maxActive: 20
#    initialSize: 1
#    maxWait: 60000
#    minIdle: 1
#    maxPoolPreparedStatementPerConnectionSize: 33
#    timeBetweenEvictionRunsMillis: 60000
#    minEvictableIdleTimeMillis: 300000
#    validationQuery: select 'x'
#    testWhileIdle: true
#    testOnBorrow: false
#    testOnReturn: false
#    poolPreparedStatements: true
#    maxOpenPreparedStatements: 20
#    filters: stat,wall,slf4j
#    removeAbandoned: true
#    logAbandoned: true
#    connectionProperties: druid.stat.mergeSql=true;stat.slowSqlMillis=500
#    useGlobalDataSourceStat: true
  rabbitmq:
    host: 120.76.154.191
    port: 5672
    username: zefun
    password: zeFUN2016
  redis:
    host: 120.76.154.191
    port: 6379
    password: zeFUN2016
server:
  port: 8095

weixin:
  platform:
    host: test.maywant.com 
    appid: wx2741a98577defffc
    secret: 1ee5695816cd4197c3e9c22d17aa48ed
    aeskey: MOxZeJ0g5FzGW0ocwMyjlq2yjJHgUNh5SSe7ZVXYSgD 
    token: zefun

---
spring:
  profiles: prod
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.10.4:3306/zefun
    #url: jdbc:mysql://zefunpro.mysql.rds.aliyuncs.com:3306/zefun
    username: zefun
    password: zeFUN2016
#    type: com.alibaba.druid.pool.DruidDataSource
#    maxActive: 20
#    initialSize: 1
#    maxWait: 60000
#    minIdle: 1
#    maxPoolPreparedStatementPerConnectionSize: 33
#    timeBetweenEvictionRunsMillis: 60000
#    minEvictableIdleTimeMillis: 300000
#    validationQuery: select 'x'
#    testWhileIdle: true
#    testOnBorrow: false
#    testOnReturn: false
#    poolPreparedStatements: true
#    maxOpenPreparedStatements: 20
#    filters: mergeStat
#    removeAbandoned: true
#    logAbandoned: true
  rabbitmq:
    host: 112.74.186.153
    port: 5672
    username: zefun
    password: zeFUN2016
  redis:
    host: 192.168.10.3
    port: 6379
    password: zeFUN2016
server:
  port: 8095

#mybatis:
#  mapper-locations: classpath:sqlMap/*.xml
#  typeAliasesPackage: com.marketing.web.mapper

weixin:
  platform:
    host: www.maywant.com 
    appid: wx55823f322f709275 
    secret: 8898c8d5cb48c5aa24dfdb75218b7129 
    aeskey: MOxZeJ0g5FzGW0ocwMyjlq2yjJHgUNh5SSe7ZVXYSgD 
    token: zefun
